# Builds and publish docker image.
name: CI

on:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker image build . --tag rdok/terraform-aws-icons:latest
    - name: Publish
      env:
        TOKEN: ${{ secrets.TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "${TOKEN}" | docker login -u "${USERNAME}" --password-stdin
        docker image push rdok/terraform-aws-icons:latest
        docker logout
